---
# From Splunk attack_range

- name: features | Installing Windows DNS Server
  win_feature:
    name: DNS
    state: present
    include_management_tools: yes
    include_sub_features: yes
  register: windows_dns_server

- name: reboot | Rebooting Server
  win_reboot:
    post_reboot_delay: 30
  when: windows_dns_server.reboot_required