---

- name: Add domain group to local Remote Desktop Users group
  win_group_membership:
    name: Remote Desktop Users
    members: 
      - "Atomic-users@{{ domain_name_short }}"
    state: present

- name: Add local administrator
  win_group_membership:
    name: Administrators
    members: 
      - "maveric@{{ domain_name_short }}"
    state: present