---

  - name: Specify DNS settings
    win_dns_client:
      adapter_names: '*'
      ipv4_addresses: 
        - "{{ private_ip_dc }}"

  - name: Join Domain
    win_domain_membership: 
      dns_domain_name: "{{ domain_name }}"
      hostname: "{{ domain_hostname }}"
      domain_admin_user: "{{ domain_admin_username }}@{{ domain_name }}"
      domain_admin_password: "{{ domain_admin_password }}"
      state: domain
    register: domain_state

  - win_reboot:
    when: domain_state.reboot_required