---

# EasyRSA
- name: easyrsa
  hosts: ovpn_server
  become: true
  roles:
    - role: easyrsa
  vars:
    easyrsa_generate_dh: true
    easyrsa_servers:
      - name: server
        cn: "{{ inventory_hostname }}"
    easyrsa_clients:
      - name: client1
      - name: client2
      - name: client3
      - name: client4
      - name: client5
      - name: client6
    easyrsa_pki_dir: /etc/easyrsa/pki
    easyrsa_conf_req_country: test
    easyrsa_conf_req_province: test
    easyrsa_conf_req_city: test
    easyrsa_conf_req_org: test
    easyrsa_conf_req_email: s
    easyrsa_conf_req_ou: sa


# OpenVPN
- name: openvpn
  hosts: ovpn_server
  become: true
  roles:
    - role: openvpn
  vars:
    openvpn_local: 10.0.0.5
    openvpn_topology: subnet
    openvpn_use_external_repo: false
    openvpn_etcdir: /etc/openvpn
    openvpn_keydir: /etc/easyrsa/pki
    openvpn_host: "{{ hostvars[inventory_hostname].ansible_host }}"
    openvpn_port: '1194'
    openvpn_proto: udp
    openvpn_dev: tun
    openvpn_server: 10.0.1.8 255.255.255.248
    openvpn_server_net: 10.0.1.8/29
    openvpn_bridge: {}
    openvpn_max_clients: 6
    openvpn_log: /var/log/openvpn.log
    openvpn_keepalive: "10 120"
    openvpn_ifconfig_pool_persist: ipp.txt
    openvpn_comp_lzo: true
    openvpn_cipher: BF-CBC
    openvpn_status: openvpn-status.log
    openvpn_verb: 3
    openvpn_user: nobody
    openvpn_group: nogroup
    openvpn_resolv_retry: infinite
    openvpn_server_options: []

    ## MANAGEMENT
    openvpn_management_enable: false
    #openvpn_management_host: 10.0.0.5
    #openvpn_management_port: 943
    #openvpn_management_pass: adv_env_ovpn_management

    ## NETWORKING
    openvpn_route_traffic: true
    openvpn_open_firewall: true
    openvpn_out_interface: eth0
    openvpn_nat_ranges:
      - 0.0.0.0/0
    openvpn_nat_address: 10.0.0.5
    openvpn_route_ranges: 
      - 10.0.0.0 255.255.252.0
    #openvpn_dns_servers: []

    ## CLIENTS
    openvpn_clients:
      - client1
      # - client2
      # - client3
      # - client4
      # - client5
      # - client6
    openvpn_clients_revoke: []
    openvpn_client_options: []
    openvpn_unified_client_profiles: true
    openvpn_download_clients: true
    openvpn_download_dir: ./certs
    openvpn_download_extract: false
    openvpn_client_to_client: true
    openvpn_client_to_client_via_ip: false
    openvpn_ccd: /etc/openvpn/ccd/
    openvpn_ccd_configs:
      - name: client1
        content:

    ## AUTHENTICATION
    openvpn_use_pam: false
    openvpn_use_pam_users: []
    openvpn_simple_auth: false
    openvpn_simple_auth_password: ""

    ## SCRIPTING
    openvpn_script_output_directories:
      - /var/log/openvpn-script-out/
    #openvpn_scripts_dir: "{{ openvpn_etcdir }}/scripts/"
    #openvpn_script_files:
    #  - scripts/client-disconnect.sh.j2
    #openvpn_inline_scripts:
    #  - name: my-up-script.sh
    #    content: |
    #      #!/usr/bin/env
    #      echo 'Up!' >> "/var/up.log"