---

- name: features | Installing AD Domain Services
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes
    state: present

- name: features | Installing RSAT AD Admin Center
  win_feature:
    name: RSAT-AD-AdminCenter
    state: present

- name: Creating a windows domain
  win_domain:
    dns_domain_name: "{{ domain_name }}"
    safe_mode_password: "{{ domain_safe_mode_password }}"

- name: Setting DNS Servers
  win_dns_client:
    adapter_names: "*"
    ipv4_addresses: "127.0.0.1"

- name: reboot | Rebooting Server
  win_reboot:
    post_reboot_delay: 300

- name: Managing Domain Controller Membership
  win_domain_controller:
    dns_domain_name: "{{ domain_name }}"
    domain_admin_user: "{{ domain_admin_username }}@{{ domain_name }}"
    domain_admin_password: "{{ domain_admin_password }}"
    safe_mode_password: "{{ domain_safe_mode_password }}"
    state: "domain_controller"
  register: windows_domain_controller

- name: reboot | Rebooting Server
  win_reboot:
  when: windows_domain_controller.reboot_required

- name: sleep for 120 seconds and continue with play
  win_wait_for:
    delay: 120
    port: 3389
    timeout: 30

- name: Switch to Domain Admin
  set_fact:
    ansible_user: "{{ domain_admin_username }}@{{ domain_name }}"
    ansible_password: "{{ domain_admin_password }}"