---
# Populate domain users

- name: Add domain groups
  win_domain_group:
    name: "{{ item }}"
    scope: global
    state: present
  loop: "{{ domain_groups }}"

- name: Add domain users
  win_domain_user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    groups: "{{ item.groups }}"
    groups_action: add
  loop: "{{ domain_users }}"
