---

- hosts: dc
  gather_facts: yes
  vars_files:
    - ./vars/domain_controller.yml
    - ./vars/domain_users.yml
    - ./vars/domain.yml
  roles:
    - windows_common
    - windows_dns
    - windows_domain_controller
    - windows_domain