---
##############################################################
## Build Windows domain environment for Adversary Emulation ##
##############################################################

## PRE TASKS

## TASKS

# Playbook: Creation and configuration of domain controller and domain.
# Install and configures a new domain controller, forest and domain,
# configures users and groups
- import_playbook: windows_dc.yml

# Playbook: Join member servers and clients to the domain
# Configures a server or client so it can be joined to the domain
- import_playbook: windows_domain_client.yml