---

- name: Ensure caldera dependencies are present
  apt:
    name: "{{ caldera_pkg }}"
    state: present
    update_cache: yes
  register: pkg_result
  become: yes
  until: pkg_result is success

- name: git clone caldera
  git:
    repo: https://github.com/mitre/caldera.git
    dest: "{{ caldera_rootdir }}"
    version: "{{ caldera_version }}"
    update: false
    recursive: true
  become: yes
  register: result

- name: Install python dependencies
  pip:
    requirements: "{{ caldera_rootdir }}/requirements.txt"
    executable: pip3

- name: Identify other pip requirements
  find:
    paths: "{{ caldera_rootdir }}/plugins"
    patterns: 'requirements.txt'
    recurse: yes
  register: requirements

- name: Install other pip requirements
  pip:
    requirements: "{{ item.path }}"
    executable: pip3
  register: pkg_result
  until: pkg_result is success
  loop: "{{ requirements.files }}"

- name: add plugin to conf
  lineinfile:
    path: "{{ caldera_rootdir }}/conf/default.yml"
    insertafter: 'plugins:'
    line: "- {{ item }}"
  with_items: "{{ plugins }}"
