---

- name: Change the hostname
  win_hostname:
    name: "{{ domain_hostname }}"
  register: hostname_changed

- name: reboot | Hostname changed
  win_reboot:
  when: hostname_changed.reboot_required